sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t harishmani09/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harishmani09/react-test npm test

after_success:
  - docker build -t harishmani09/multi-client ./client
  - docker build -t harishmani09/multi-nginx ./nginx
  - docker build -t harishmani09/multi-server ./server
  - docker build -t harishmani09/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push harishmani09/multi-nginx
  - docker push harishmani09/multi-client
  - docker push harishmani09/multi-server
  - docker push harishmani09/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'Multi-Docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-391160630794'
  bucket_path: 'docker_multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    
